# downloader.
FROM ubuntu:latest AS downloader
ENV WORKDIR=/root
WORKDIR ${WORKDIR}
COPY . ${WORKDIR}
RUN apt -y update                                                                             && \
    curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash  && \
    apt install -y git-lfs                                                                    && \
    rm -f .git/hooks                                                                          && \
    git lfs install                                                                           && \
    git lfs pull                                                                              && \
    git submodule update --init --recursive

# runtime.
FROM nvidia/cuda:12.6.3-cudnn-runtime-ubuntu22.04
ENV WORKDIR=/root
WORKDIR ${WORKDIR}
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime                          && \
    apt-get update                                                                   && \
    apt-get install -y python3.11                                                    && \
    python3.11 -m venv venv                                                          
COPY --from=downloader ${WORKDIR} ${WORKDIR}                                    
RUN . venv/bin/activate                                                              && \
    pip install torch torchvision --index-url https://download.pytorch.org/whl/cu126 && \
    # apt-get install -y libgl1-mesa-glx                                               && \
    pip install -r requirements.txt                                                  && \
    apt-get clean

CMD ["bash", "run.bash"]
