# builder.
FROM nvidia/cuda:12.6.0-runtime-ubi8 AS builder
ENV WORKDIR=/root
WORKDIR ${WORKDIR}
COPY . ${WORKDIR}
RUN yum -y update                                                                             && \
    curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.rpm.sh | bash  && \
    yum install -y git-lfs                                                                    && \
    git lfs install                                                                           && \
    git lfs pull                                                                              && \
    git submodule update --init --recursive

# runtime.
FROM nvidia/cuda:12.6.0-runtime-ubi8
ENV WORKDIR=/root
WORKDIR ${WORKDIR}
COPY --from=builder ${WORKDIR} ${WORKDIR}
ENV PATH="${WORKDIR}/venv/bin:$PATH"
RUN echo "ZONE=Asia/Shanghai" >> /etc/sysconfig/clock         && \
    rm -f /etc/localtime                                      && \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime   && \
    yum -y update                                             && \
    yum install python39 python39-pip -y                      && \
    python3.9 -m venv venv                                    && \
    pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cu126 && \
    yum install -y mesa-libGL                                 && \
    pip3 install -r requirements.txt                          && \
    yum clean all

CMD ["bash", "run.bash"]
