[build]
target = "x86_64-pc-windows-msvc"

[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C", "target-feature=+crt-static"
]

[env]
CARGO_CFG_WINDOWS = "1"
# Skip VS detection to avoid vswhom-sys issues
VSWHERE = "false"
VS_UNICODE_OUTPUT = "1"
