// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: api/v1/model_service.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceStatus int32

const (
	ServiceStatus_SERVICE_STATUS_UNSPECIFIED          ServiceStatus = 0
	ServiceStatus_SERVICE_STATUS_SUCCESS              ServiceStatus = 1
	ServiceStatus_SERVICE_STATUS_INVALID_CONTENT_TYPE ServiceStatus = 2
	ServiceStatus_SERVICE_STATUS_MISSING_IMAGE_DATA   ServiceStatus = 3
	ServiceStatus_SERVICE_STATUS_INVALID_IMAGE_FORMAT ServiceStatus = 4
	ServiceStatus_SERVICE_STATUS_NO_OBJECT_DETECTED   ServiceStatus = 5
	ServiceStatus_SERVICE_STATUS_MODEL_NOT_FOUND      ServiceStatus = 6
	ServiceStatus_SERVICE_STATUS_STREAM_ERROR         ServiceStatus = 7
)

// Enum value maps for ServiceStatus.
var (
	ServiceStatus_name = map[int32]string{
		0: "SERVICE_STATUS_UNSPECIFIED",
		1: "SERVICE_STATUS_SUCCESS",
		2: "SERVICE_STATUS_INVALID_CONTENT_TYPE",
		3: "SERVICE_STATUS_MISSING_IMAGE_DATA",
		4: "SERVICE_STATUS_INVALID_IMAGE_FORMAT",
		5: "SERVICE_STATUS_NO_OBJECT_DETECTED",
		6: "SERVICE_STATUS_MODEL_NOT_FOUND",
		7: "SERVICE_STATUS_STREAM_ERROR",
	}
	ServiceStatus_value = map[string]int32{
		"SERVICE_STATUS_UNSPECIFIED":          0,
		"SERVICE_STATUS_SUCCESS":              1,
		"SERVICE_STATUS_INVALID_CONTENT_TYPE": 2,
		"SERVICE_STATUS_MISSING_IMAGE_DATA":   3,
		"SERVICE_STATUS_INVALID_IMAGE_FORMAT": 4,
		"SERVICE_STATUS_NO_OBJECT_DETECTED":   5,
		"SERVICE_STATUS_MODEL_NOT_FOUND":      6,
		"SERVICE_STATUS_STREAM_ERROR":         7,
	}
)

func (x ServiceStatus) Enum() *ServiceStatus {
	p := new(ServiceStatus)
	*p = x
	return p
}

func (x ServiceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_model_service_proto_enumTypes[0].Descriptor()
}

func (ServiceStatus) Type() protoreflect.EnumType {
	return &file_api_v1_model_service_proto_enumTypes[0]
}

func (x ServiceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceStatus.Descriptor instead.
func (ServiceStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_model_service_proto_rawDescGZIP(), []int{0}
}

type ModelType int32

const (
	ModelType_MODEL_TYPE_UNSPECIFIED ModelType = 0
	ModelType_MODEL_TYPE_GESTURE     ModelType = 1
	ModelType_MODEL_TYPE_PONDING     ModelType = 2
	ModelType_MODEL_TYPE_SMOKE       ModelType = 3
	ModelType_MODEL_TYPE_MOUSE       ModelType = 4
	ModelType_MODEL_TYPE_TSHIRT      ModelType = 5
	ModelType_MODEL_TYPE_CIGAR       ModelType = 6
	ModelType_MODEL_TYPE_HELMET      ModelType = 7
	ModelType_MODEL_TYPE_FIRE        ModelType = 8
	ModelType_MODEL_TYPE_FALL        ModelType = 9
	ModelType_MODEL_TYPE_SAFETYBELT  ModelType = 10
)

// Enum value maps for ModelType.
var (
	ModelType_name = map[int32]string{
		0:  "MODEL_TYPE_UNSPECIFIED",
		1:  "MODEL_TYPE_GESTURE",
		2:  "MODEL_TYPE_PONDING",
		3:  "MODEL_TYPE_SMOKE",
		4:  "MODEL_TYPE_MOUSE",
		5:  "MODEL_TYPE_TSHIRT",
		6:  "MODEL_TYPE_CIGAR",
		7:  "MODEL_TYPE_HELMET",
		8:  "MODEL_TYPE_FIRE",
		9:  "MODEL_TYPE_FALL",
		10: "MODEL_TYPE_SAFETYBELT",
	}
	ModelType_value = map[string]int32{
		"MODEL_TYPE_UNSPECIFIED": 0,
		"MODEL_TYPE_GESTURE":     1,
		"MODEL_TYPE_PONDING":     2,
		"MODEL_TYPE_SMOKE":       3,
		"MODEL_TYPE_MOUSE":       4,
		"MODEL_TYPE_TSHIRT":      5,
		"MODEL_TYPE_CIGAR":       6,
		"MODEL_TYPE_HELMET":      7,
		"MODEL_TYPE_FIRE":        8,
		"MODEL_TYPE_FALL":        9,
		"MODEL_TYPE_SAFETYBELT":  10,
	}
)

func (x ModelType) Enum() *ModelType {
	p := new(ModelType)
	*p = x
	return p
}

func (x ModelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModelType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_model_service_proto_enumTypes[1].Descriptor()
}

func (ModelType) Type() protoreflect.EnumType {
	return &file_api_v1_model_service_proto_enumTypes[1]
}

func (x ModelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModelType.Descriptor instead.
func (ModelType) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_model_service_proto_rawDescGZIP(), []int{1}
}

// normalized xyxyn format
type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Left          float64                `protobuf:"fixed64,1,opt,name=left,proto3" json:"left,omitempty"`
	Top           float64                `protobuf:"fixed64,2,opt,name=top,proto3" json:"top,omitempty"`
	Width         float64                `protobuf:"fixed64,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        float64                `protobuf:"fixed64,4,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_api_v1_model_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_model_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_api_v1_model_service_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetLeft() float64 {
	if x != nil {
		return x.Left
	}
	return 0
}

func (x *Location) GetTop() float64 {
	if x != nil {
		return x.Top
	}
	return 0
}

func (x *Location) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Location) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type DetectionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         float64                `protobuf:"fixed64,1,opt,name=score,proto3" json:"score,omitempty"`
	Location      *Location              `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	ClassName     *string                `protobuf:"bytes,3,opt,name=class_name,json=className,proto3,oneof" json:"class_name,omitempty"` // for models that return class names
	ClassId       *int32                 `protobuf:"varint,4,opt,name=class_id,json=classId,proto3,oneof" json:"class_id,omitempty"`      // for models that return class indices
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectionResult) Reset() {
	*x = DetectionResult{}
	mi := &file_api_v1_model_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionResult) ProtoMessage() {}

func (x *DetectionResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_model_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionResult.ProtoReflect.Descriptor instead.
func (*DetectionResult) Descriptor() ([]byte, []int) {
	return file_api_v1_model_service_proto_rawDescGZIP(), []int{1}
}

func (x *DetectionResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *DetectionResult) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *DetectionResult) GetClassName() string {
	if x != nil && x.ClassName != nil {
		return *x.ClassName
	}
	return ""
}

func (x *DetectionResult) GetClassId() int32 {
	if x != nil && x.ClassId != nil {
		return *x.ClassId
	}
	return 0
}

type ModelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ModelType              `protobuf:"varint,1,opt,name=type,proto3,enum=api.v1.ModelType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelInfo) Reset() {
	*x = ModelInfo{}
	mi := &file_api_v1_model_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfo) ProtoMessage() {}

func (x *ModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_model_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfo.ProtoReflect.Descriptor instead.
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return file_api_v1_model_service_proto_rawDescGZIP(), []int{2}
}

func (x *ModelInfo) GetType() ModelType {
	if x != nil {
		return x.Type
	}
	return ModelType_MODEL_TYPE_UNSPECIFIED
}

func (x *ModelInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ModelInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Streaming inference request
type InferenceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// session identifier for stateful models like FALL
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Types that are valid to be assigned to Request:
	//
	//	*InferenceRequest_Init
	//	*InferenceRequest_Frame
	//	*InferenceRequest_Close
	Request       isInferenceRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferenceRequest) Reset() {
	*x = InferenceRequest{}
	mi := &file_api_v1_model_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceRequest) ProtoMessage() {}

func (x *InferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_model_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceRequest.ProtoReflect.Descriptor instead.
func (*InferenceRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_model_service_proto_rawDescGZIP(), []int{3}
}

func (x *InferenceRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *InferenceRequest) GetRequest() isInferenceRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *InferenceRequest) GetInit() *StreamInitRequest {
	if x != nil {
		if x, ok := x.Request.(*InferenceRequest_Init); ok {
			return x.Init
		}
	}
	return nil
}

func (x *InferenceRequest) GetFrame() *FrameData {
	if x != nil {
		if x, ok := x.Request.(*InferenceRequest_Frame); ok {
			return x.Frame
		}
	}
	return nil
}

func (x *InferenceRequest) GetClose() *StreamCloseRequest {
	if x != nil {
		if x, ok := x.Request.(*InferenceRequest_Close); ok {
			return x.Close
		}
	}
	return nil
}

type isInferenceRequest_Request interface {
	isInferenceRequest_Request()
}

type InferenceRequest_Init struct {
	Init *StreamInitRequest `protobuf:"bytes,2,opt,name=init,proto3,oneof"`
}

type InferenceRequest_Frame struct {
	Frame *FrameData `protobuf:"bytes,3,opt,name=frame,proto3,oneof"`
}

type InferenceRequest_Close struct {
	Close *StreamCloseRequest `protobuf:"bytes,4,opt,name=close,proto3,oneof"`
}

func (*InferenceRequest_Init) isInferenceRequest_Request() {}

func (*InferenceRequest_Frame) isInferenceRequest_Request() {}

func (*InferenceRequest_Close) isInferenceRequest_Request() {}

type StreamInitRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ModelType ModelType              `protobuf:"varint,1,opt,name=model_type,json=modelType,proto3,enum=api.v1.ModelType" json:"model_type,omitempty"`
	// additional model-specific parameters
	Parameters    map[string]string `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamInitRequest) Reset() {
	*x = StreamInitRequest{}
	mi := &file_api_v1_model_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamInitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInitRequest) ProtoMessage() {}

func (x *StreamInitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_model_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamInitRequest.ProtoReflect.Descriptor instead.
func (*StreamInitRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_model_service_proto_rawDescGZIP(), []int{4}
}

func (x *StreamInitRequest) GetModelType() ModelType {
	if x != nil {
		return x.ModelType
	}
	return ModelType_MODEL_TYPE_UNSPECIFIED
}

func (x *StreamInitRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type FrameData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// raw image bytes (jpg/png encoded)
	ImageData     []byte `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameData) Reset() {
	*x = FrameData{}
	mi := &file_api_v1_model_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameData) ProtoMessage() {}

func (x *FrameData) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_model_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameData.ProtoReflect.Descriptor instead.
func (*FrameData) Descriptor() ([]byte, []int) {
	return file_api_v1_model_service_proto_rawDescGZIP(), []int{5}
}

func (x *FrameData) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

type StreamCloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamCloseRequest) Reset() {
	*x = StreamCloseRequest{}
	mi := &file_api_v1_model_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamCloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamCloseRequest) ProtoMessage() {}

func (x *StreamCloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_model_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamCloseRequest.ProtoReflect.Descriptor instead.
func (*StreamCloseRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_model_service_proto_rawDescGZIP(), []int{6}
}

func (x *StreamCloseRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Streaming inference response
type InferenceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*InferenceResponse_Init
	//	*InferenceResponse_Detection
	//	*InferenceResponse_Error
	//	*InferenceResponse_Close
	Response      isInferenceResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferenceResponse) Reset() {
	*x = InferenceResponse{}
	mi := &file_api_v1_model_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceResponse) ProtoMessage() {}

func (x *InferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_model_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceResponse.ProtoReflect.Descriptor instead.
func (*InferenceResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_model_service_proto_rawDescGZIP(), []int{7}
}

func (x *InferenceResponse) GetResponse() isInferenceResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *InferenceResponse) GetInit() *StreamInitResponse {
	if x != nil {
		if x, ok := x.Response.(*InferenceResponse_Init); ok {
			return x.Init
		}
	}
	return nil
}

func (x *InferenceResponse) GetDetection() *DetectionResponse {
	if x != nil {
		if x, ok := x.Response.(*InferenceResponse_Detection); ok {
			return x.Detection
		}
	}
	return nil
}

func (x *InferenceResponse) GetError() *StreamErrorResponse {
	if x != nil {
		if x, ok := x.Response.(*InferenceResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *InferenceResponse) GetClose() *StreamCloseResponse {
	if x != nil {
		if x, ok := x.Response.(*InferenceResponse_Close); ok {
			return x.Close
		}
	}
	return nil
}

type isInferenceResponse_Response interface {
	isInferenceResponse_Response()
}

type InferenceResponse_Init struct {
	Init *StreamInitResponse `protobuf:"bytes,1,opt,name=init,proto3,oneof"`
}

type InferenceResponse_Detection struct {
	Detection *DetectionResponse `protobuf:"bytes,2,opt,name=detection,proto3,oneof"`
}

type InferenceResponse_Error struct {
	Error *StreamErrorResponse `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type InferenceResponse_Close struct {
	Close *StreamCloseResponse `protobuf:"bytes,4,opt,name=close,proto3,oneof"`
}

func (*InferenceResponse_Init) isInferenceResponse_Response() {}

func (*InferenceResponse_Detection) isInferenceResponse_Response() {}

func (*InferenceResponse_Error) isInferenceResponse_Response() {}

func (*InferenceResponse_Close) isInferenceResponse_Response() {}

type StreamInitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        ServiceStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=api.v1.ServiceStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamInitResponse) Reset() {
	*x = StreamInitResponse{}
	mi := &file_api_v1_model_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamInitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInitResponse) ProtoMessage() {}

func (x *StreamInitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_model_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamInitResponse.ProtoReflect.Descriptor instead.
func (*StreamInitResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_model_service_proto_rawDescGZIP(), []int{8}
}

func (x *StreamInitResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StreamInitResponse) GetStatus() ServiceStatus {
	if x != nil {
		return x.Status
	}
	return ServiceStatus_SERVICE_STATUS_UNSPECIFIED
}

type DetectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        ServiceStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=api.v1.ServiceStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Results       []*DetectionResult     `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ApiVersion    string                 `protobuf:"bytes,6,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	ModelVersion  string                 `protobuf:"bytes,7,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectionResponse) Reset() {
	*x = DetectionResponse{}
	mi := &file_api_v1_model_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionResponse) ProtoMessage() {}

func (x *DetectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_model_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionResponse.ProtoReflect.Descriptor instead.
func (*DetectionResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_model_service_proto_rawDescGZIP(), []int{9}
}

func (x *DetectionResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *DetectionResponse) GetStatus() ServiceStatus {
	if x != nil {
		return x.Status
	}
	return ServiceStatus_SERVICE_STATUS_UNSPECIFIED
}

func (x *DetectionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DetectionResponse) GetResults() []*DetectionResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *DetectionResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DetectionResponse) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *DetectionResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

type StreamErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        ServiceStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=api.v1.ServiceStatus" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamErrorResponse) Reset() {
	*x = StreamErrorResponse{}
	mi := &file_api_v1_model_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamErrorResponse) ProtoMessage() {}

func (x *StreamErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_model_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamErrorResponse.ProtoReflect.Descriptor instead.
func (*StreamErrorResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_model_service_proto_rawDescGZIP(), []int{10}
}

func (x *StreamErrorResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StreamErrorResponse) GetStatus() ServiceStatus {
	if x != nil {
		return x.Status
	}
	return ServiceStatus_SERVICE_STATUS_UNSPECIFIED
}

func (x *StreamErrorResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type StreamCloseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamCloseResponse) Reset() {
	*x = StreamCloseResponse{}
	mi := &file_api_v1_model_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamCloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamCloseResponse) ProtoMessage() {}

func (x *StreamCloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_model_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamCloseResponse.ProtoReflect.Descriptor instead.
func (*StreamCloseResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_model_service_proto_rawDescGZIP(), []int{11}
}

func (x *StreamCloseResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StreamCloseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// List available models
type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_api_v1_model_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_model_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_model_service_proto_rawDescGZIP(), []int{12}
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*ModelInfo           `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	ServerVersion string                 `protobuf:"bytes,2,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_api_v1_model_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_model_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_model_service_proto_rawDescGZIP(), []int{13}
}

func (x *ListModelsResponse) GetModels() []*ModelInfo {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *ListModelsResponse) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

var File_api_v1_model_service_proto protoreflect.FileDescriptor

const file_api_v1_model_service_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/v1/model_service.proto\x12\x06api.v1\"^\n" +
	"\bLocation\x12\x12\n" +
	"\x04left\x18\x01 \x01(\x01R\x04left\x12\x10\n" +
	"\x03top\x18\x02 \x01(\x01R\x03top\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x01R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x01R\x06height\"\xb5\x01\n" +
	"\x0fDetectionResult\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x01R\x05score\x12,\n" +
	"\blocation\x18\x02 \x01(\v2\x10.api.v1.LocationR\blocation\x12\"\n" +
	"\n" +
	"class_name\x18\x03 \x01(\tH\x00R\tclassName\x88\x01\x01\x12\x1e\n" +
	"\bclass_id\x18\x04 \x01(\x05H\x01R\aclassId\x88\x01\x01B\r\n" +
	"\v_class_nameB\v\n" +
	"\t_class_id\"\x82\x01\n" +
	"\tModelInfo\x12%\n" +
	"\x04type\x18\x01 \x01(\x0e2\x11.api.v1.ModelTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"\xcc\x01\n" +
	"\x10InferenceRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12/\n" +
	"\x04init\x18\x02 \x01(\v2\x19.api.v1.StreamInitRequestH\x00R\x04init\x12)\n" +
	"\x05frame\x18\x03 \x01(\v2\x11.api.v1.FrameDataH\x00R\x05frame\x122\n" +
	"\x05close\x18\x04 \x01(\v2\x1a.api.v1.StreamCloseRequestH\x00R\x05closeB\t\n" +
	"\arequest\"\xcf\x01\n" +
	"\x11StreamInitRequest\x120\n" +
	"\n" +
	"model_type\x18\x01 \x01(\x0e2\x11.api.v1.ModelTypeR\tmodelType\x12I\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v2).api.v1.StreamInitRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"*\n" +
	"\tFrameData\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\",\n" +
	"\x12StreamCloseRequest\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\xf6\x01\n" +
	"\x11InferenceResponse\x120\n" +
	"\x04init\x18\x01 \x01(\v2\x1a.api.v1.StreamInitResponseH\x00R\x04init\x129\n" +
	"\tdetection\x18\x02 \x01(\v2\x19.api.v1.DetectionResponseH\x00R\tdetection\x123\n" +
	"\x05error\x18\x03 \x01(\v2\x1b.api.v1.StreamErrorResponseH\x00R\x05error\x123\n" +
	"\x05close\x18\x04 \x01(\v2\x1b.api.v1.StreamCloseResponseH\x00R\x05closeB\n" +
	"\n" +
	"\bresponse\"b\n" +
	"\x12StreamInitResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.api.v1.ServiceStatusR\x06status\"\x8c\x02\n" +
	"\x11DetectionResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.api.v1.ServiceStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x121\n" +
	"\aresults\x18\x04 \x03(\v2\x17.api.v1.DetectionResultR\aresults\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vapi_version\x18\x06 \x01(\tR\n" +
	"apiVersion\x12#\n" +
	"\rmodel_version\x18\a \x01(\tR\fmodelVersion\"\x82\x01\n" +
	"\x13StreamErrorResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.api.v1.ServiceStatusR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"H\n" +
	"\x13StreamCloseResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x13\n" +
	"\x11ListModelsRequest\"f\n" +
	"\x12ListModelsResponse\x12)\n" +
	"\x06models\x18\x01 \x03(\v2\x11.api.v1.ModelInfoR\x06models\x12%\n" +
	"\x0eserver_version\x18\x02 \x01(\tR\rserverVersion*\xb0\x02\n" +
	"\rServiceStatus\x12\x1e\n" +
	"\x1aSERVICE_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SERVICE_STATUS_SUCCESS\x10\x01\x12'\n" +
	"#SERVICE_STATUS_INVALID_CONTENT_TYPE\x10\x02\x12%\n" +
	"!SERVICE_STATUS_MISSING_IMAGE_DATA\x10\x03\x12'\n" +
	"#SERVICE_STATUS_INVALID_IMAGE_FORMAT\x10\x04\x12%\n" +
	"!SERVICE_STATUS_NO_OBJECT_DETECTED\x10\x05\x12\"\n" +
	"\x1eSERVICE_STATUS_MODEL_NOT_FOUND\x10\x06\x12\x1f\n" +
	"\x1bSERVICE_STATUS_STREAM_ERROR\x10\a*\x8c\x02\n" +
	"\tModelType\x12\x1a\n" +
	"\x16MODEL_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12MODEL_TYPE_GESTURE\x10\x01\x12\x16\n" +
	"\x12MODEL_TYPE_PONDING\x10\x02\x12\x14\n" +
	"\x10MODEL_TYPE_SMOKE\x10\x03\x12\x14\n" +
	"\x10MODEL_TYPE_MOUSE\x10\x04\x12\x15\n" +
	"\x11MODEL_TYPE_TSHIRT\x10\x05\x12\x14\n" +
	"\x10MODEL_TYPE_CIGAR\x10\x06\x12\x15\n" +
	"\x11MODEL_TYPE_HELMET\x10\a\x12\x13\n" +
	"\x0fMODEL_TYPE_FIRE\x10\b\x12\x13\n" +
	"\x0fMODEL_TYPE_FALL\x10\t\x12\x19\n" +
	"\x15MODEL_TYPE_SAFETYBELT\x10\n" +
	"2\xa2\x01\n" +
	"\x15ModelInferenceService\x12C\n" +
	"\n" +
	"ListModels\x12\x19.api.v1.ListModelsRequest\x1a\x1a.api.v1.ListModelsResponse\x12D\n" +
	"\tInference\x12\x18.api.v1.InferenceRequest\x1a\x19.api.v1.InferenceResponse(\x010\x01B\x83\x01\n" +
	"\n" +
	"com.api.v1B\x11ModelServiceProtoP\x01Z)github.com/inference/service/api/v1;apiv1\xa2\x02\x03AXX\xaa\x02\x06Api.V1\xca\x02\x06Api\\V1\xe2\x02\x12Api\\V1\\GPBMetadata\xea\x02\aApi::V1b\x06proto3"

var (
	file_api_v1_model_service_proto_rawDescOnce sync.Once
	file_api_v1_model_service_proto_rawDescData []byte
)

func file_api_v1_model_service_proto_rawDescGZIP() []byte {
	file_api_v1_model_service_proto_rawDescOnce.Do(func() {
		file_api_v1_model_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_model_service_proto_rawDesc), len(file_api_v1_model_service_proto_rawDesc)))
	})
	return file_api_v1_model_service_proto_rawDescData
}

var file_api_v1_model_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_v1_model_service_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_v1_model_service_proto_goTypes = []any{
	(ServiceStatus)(0),          // 0: api.v1.ServiceStatus
	(ModelType)(0),              // 1: api.v1.ModelType
	(*Location)(nil),            // 2: api.v1.Location
	(*DetectionResult)(nil),     // 3: api.v1.DetectionResult
	(*ModelInfo)(nil),           // 4: api.v1.ModelInfo
	(*InferenceRequest)(nil),    // 5: api.v1.InferenceRequest
	(*StreamInitRequest)(nil),   // 6: api.v1.StreamInitRequest
	(*FrameData)(nil),           // 7: api.v1.FrameData
	(*StreamCloseRequest)(nil),  // 8: api.v1.StreamCloseRequest
	(*InferenceResponse)(nil),   // 9: api.v1.InferenceResponse
	(*StreamInitResponse)(nil),  // 10: api.v1.StreamInitResponse
	(*DetectionResponse)(nil),   // 11: api.v1.DetectionResponse
	(*StreamErrorResponse)(nil), // 12: api.v1.StreamErrorResponse
	(*StreamCloseResponse)(nil), // 13: api.v1.StreamCloseResponse
	(*ListModelsRequest)(nil),   // 14: api.v1.ListModelsRequest
	(*ListModelsResponse)(nil),  // 15: api.v1.ListModelsResponse
	nil,                         // 16: api.v1.StreamInitRequest.ParametersEntry
}
var file_api_v1_model_service_proto_depIdxs = []int32{
	2,  // 0: api.v1.DetectionResult.location:type_name -> api.v1.Location
	1,  // 1: api.v1.ModelInfo.type:type_name -> api.v1.ModelType
	6,  // 2: api.v1.InferenceRequest.init:type_name -> api.v1.StreamInitRequest
	7,  // 3: api.v1.InferenceRequest.frame:type_name -> api.v1.FrameData
	8,  // 4: api.v1.InferenceRequest.close:type_name -> api.v1.StreamCloseRequest
	1,  // 5: api.v1.StreamInitRequest.model_type:type_name -> api.v1.ModelType
	16, // 6: api.v1.StreamInitRequest.parameters:type_name -> api.v1.StreamInitRequest.ParametersEntry
	10, // 7: api.v1.InferenceResponse.init:type_name -> api.v1.StreamInitResponse
	11, // 8: api.v1.InferenceResponse.detection:type_name -> api.v1.DetectionResponse
	12, // 9: api.v1.InferenceResponse.error:type_name -> api.v1.StreamErrorResponse
	13, // 10: api.v1.InferenceResponse.close:type_name -> api.v1.StreamCloseResponse
	0,  // 11: api.v1.StreamInitResponse.status:type_name -> api.v1.ServiceStatus
	0,  // 12: api.v1.DetectionResponse.status:type_name -> api.v1.ServiceStatus
	3,  // 13: api.v1.DetectionResponse.results:type_name -> api.v1.DetectionResult
	0,  // 14: api.v1.StreamErrorResponse.status:type_name -> api.v1.ServiceStatus
	4,  // 15: api.v1.ListModelsResponse.models:type_name -> api.v1.ModelInfo
	14, // 16: api.v1.ModelInferenceService.ListModels:input_type -> api.v1.ListModelsRequest
	5,  // 17: api.v1.ModelInferenceService.Inference:input_type -> api.v1.InferenceRequest
	15, // 18: api.v1.ModelInferenceService.ListModels:output_type -> api.v1.ListModelsResponse
	9,  // 19: api.v1.ModelInferenceService.Inference:output_type -> api.v1.InferenceResponse
	18, // [18:20] is the sub-list for method output_type
	16, // [16:18] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_api_v1_model_service_proto_init() }
func file_api_v1_model_service_proto_init() {
	if File_api_v1_model_service_proto != nil {
		return
	}
	file_api_v1_model_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_v1_model_service_proto_msgTypes[3].OneofWrappers = []any{
		(*InferenceRequest_Init)(nil),
		(*InferenceRequest_Frame)(nil),
		(*InferenceRequest_Close)(nil),
	}
	file_api_v1_model_service_proto_msgTypes[7].OneofWrappers = []any{
		(*InferenceResponse_Init)(nil),
		(*InferenceResponse_Detection)(nil),
		(*InferenceResponse_Error)(nil),
		(*InferenceResponse_Close)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_model_service_proto_rawDesc), len(file_api_v1_model_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_model_service_proto_goTypes,
		DependencyIndexes: file_api_v1_model_service_proto_depIdxs,
		EnumInfos:         file_api_v1_model_service_proto_enumTypes,
		MessageInfos:      file_api_v1_model_service_proto_msgTypes,
	}.Build()
	File_api_v1_model_service_proto = out.File
	file_api_v1_model_service_proto_goTypes = nil
	file_api_v1_model_service_proto_depIdxs = nil
}
